// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_STM_INPUTPARSER_H
#define TEST_STM_INPUTPARSER_H

#include "stdinc.h"
#include "segment.h"
#include "speech.h"
#include "token.h"
#include "stm_inputparser.h"

/**
 * Test the STM input parser
 */
class STMInputParserTest
{
	public:
		// class constructor
		STMInputParserTest();
		// class destructor
		~STMInputParserTest();
		/**
		 * Launch all the test of STM input parser
		 */
		void testAll();
		/**
		 * Test the import of the Basic file
		 */
		void testBasicImport();
};

#endif // TEST_STM_INPUTPARSER_H
