// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_GRAPHALIGNEDTOKEN_H
#define TEST_GRAPHALIGNEDTOKEN_H

#include "stdinc.h"
#include "graphalignedtoken.h"
#include "speechset.h"

/**
 * Test the GraphAlignedSegment class
 */
class GraphAlignedTokenTest
{
	public:
		// class constructor
		GraphAlignedTokenTest();
		// class destructor
		~GraphAlignedTokenTest();
		/**
		 * Launch all the test methods on GraphAlignedToken
		 */
		void testAll();
		/**
		 * Test the behavior of the Equal operator on GraphAlignedToken
		 */
		void testEqualOperator();
};

#endif // TEST_GRAPHALIGNEDTOKEN_H
