// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_GRAPHALIGNEDSEGMENT_H
#define TEST_GRAPHALIGNEDSEGMENT_H

#include "stdinc.h"
#include "graphalignedsegment.h"
#include "speechset.h"

/**
 * Test the GraphAlignedSegment Object.
 */
class GraphAlignedSegmentTest
{
	public:
		// class constructor
		GraphAlignedSegmentTest();
		// class destructor
		~GraphAlignedSegmentTest();
		/**
		 * Launch all the tests on GraphAlignedSegmentTest
		 */
		void testAll();
		/**
		 * Test the Equal operator behavior.
		 */
		void testEqualOperator();
};

#endif // TEST_GRAPHALIGNEDSEGMENT_H
