// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_TRNTRN_SEGMENTOR_H
#define TEST_TRNTRN_SEGMENTOR_H

#include "trntrn_segmentor.h"

/**
 * Test the TRN to TRN segmentor.
 */
class TRNTRNSegmentorTest
{
	public:
		// class constructor
		TRNTRNSegmentorTest();
		// class destructor
		~TRNTRNSegmentorTest();
		/**
		 * Launch all the tests on the TRN to TRN segmentor
		 */
		void testAll();
		/**
		 * Test the case where the segmentor need to align 2 segments to
		 * 2 segments.
		 */
		void test2segmentsCase();
		/*
		* Test the case where the segmentor need to align 4 segments to
		* 4 segments. there are affected to 2 different speakers
		*/
		void test4segments2spkrCase();
};

#endif // TEST_TRNTRN_SEGMENTOR_H
