// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_PROPERTIES_H
#define TEST_PROPERTIES_H

#include "stdinc.h"
#include "properties.h"

/**
 * Test the properties Object.
 */
class PropertiesTest
{
	public:
		// class constructor
		PropertiesTest();
		// class destructor
		~PropertiesTest();
		/**
		 * Launch all the tests on the properties
		 */
		void testAll();
		/**
		 * Test the accessor of the properties
		 */
		void testAccessMethods();
};

#endif // TEST_PROPERTIES_H
