// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_LEVENSHTEIN_H
#define TEST_LEVENSHTEIN_H

#include "stdinc.h"
#include "std_benchmark.h"
#include "levenshtein.h"
#include "graphalignedsegment.h"
#include "speakermatch.h"

/**
 * Tests the Levenshtein algo with a benchmark.
 */
class LevenshteinTest
{
	public:
		// class constructor
		LevenshteinTest();
		// class destructor
		~LevenshteinTest();
		void TestBasicBenchmark();
		void TestAll();
		void TestGAS();
};

#endif // TEST_LEVENSHTEIN_H
