// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_TRN_INPUTPARSER_H
#define TEST_TRN_INPUTPARSER_H

#include "trn_inputparser.h"
#include "token.h"
#include "speech.h"
#include "segment.h"

/**
 * Test the TRN input parser.
 */
class TRNInputParserTest
{
	public:
		// class constructor
		TRNInputParserTest();
		// class destructor
		~TRNInputParserTest();
		/**
		 * Launch all the tests on the TRN input parser
		 */
		void testAll();
		/**
		 * Test the import of the Basic trn file.
		 */
		void testBasicImport();
};

#endif // TEST_TRN_INPUTPARSER_H
