// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEST_CTM_INPUTPARSER_H
#define TEST_CTM_INPUTPARSER_H

#include "stdinc.h"
#include "segment.h"
#include "speech.h"
#include "token.h"
#include "ctm_inputparser.h"

/**
 * Test the CTM input parser
 */
class CTMInputParserTest
{
	public:
		// class constructor
		CTMInputParserTest();
		// class destructor
		~CTMInputParserTest();
		/**
		 * Launch all test
		 */
		void testAll();
		/**
		 * Test the import of the Basic file
		 */
		void testBasicImport();
};

#endif // TEST_CTM_INPUTPARSER_H
